version: "3.3"

services:
  postgresql:
    image: postgres:13.1
    container_name: spring-data-jdbc-demo-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - "5434:5432"